version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run: mvn clean test 
               - run:
               name: Publish Code Coverage to Codecov
               command: |
                 bash <(curl -s https://codecov.io/bash) -t ${codedev}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
