version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build_and_upload_coverage:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean test

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_upload_coverage:
          filters:
            branches:
              only:
                - master

