version: 2.1

orbs:
  codecov: codecov/codecov@x.y.z  # Replace x.y.z with the latest version

jobs:
  build_and_upload_coverage:
    docker:
      - image: cimg/openjdk:8.0  # Using CircleCI's next-gen image
    steps:
      - checkout
      - run:
          name: Run Maven Clean and Package  # This name field is optional
          command: mvn clean package
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # Assuming this is the path to your coverage report

workflows:
  version: 2
  my_workflow:
    jobs:
      - build_and_upload_coverage
