version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
