version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  

    branches:
      only:
        - master  

    steps:
      - checkout  

      - run:
          name: Setup JDK 8
          command: |
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-8-oracle-x64/bin/java 100
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-8-oracle-x64/bin/javac 100

      - run:
          name: Execute Maven Tests
          command: mvn test  
